language: rust
rust:
  - nightly
  - beta
  - stable
script:
  - cargo build
  - "if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo test; fi"
  - cargo doc
after_success:
  - curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh
notifications:
  webhooks: http://build.servo.org:54856/travis
